version: "3.3"
services:
   jivejdondb:
      image: mysql
      ports:
        - "3306:3306"
      environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: jivejdon
       MYSQL_USER: test
       MYSQL_PASSWORD: test
      volumes:
        - /mysql:/docker-entrypoint-initdb.d     
   jivejdon:
      depends_on:
       - jivejdondb
      build:
        context: .
      volumes:
        - ./target/ROOT.war:/usr/local/tomcat/webapps/ROOT.war   
   
