version: "3.3"

services:

  mavenjivejdon:
     build:
        context: .
        dockerfile: Dockerfile_maven 

  database:
     build:
        context: .
        dockerfile: Dockerfile_mysql 
   

  webserver:
      build:
        context: .
        dockerfile: Dockerfile_tomcat 
   
