version: "3.3"
services:
   mysql:
      image: mysql
      ports:
        - "3306:3306"
      environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: jivejdon
       MYSQL_USER: test
       MYSQL_PASSWORD: test
    
      volumes:
        - ./mysql:/docker-entrypoint-initdb.d 
        - mysql-data:/var/lib/mysql                         
   
   tomcat:
       image: tomcat
       container_name: tomcat
       ports:
        - 8080:8080
       volumes:
        - ../target/ROOT.war:/usr/local/tomcat/webapps/ROOT.war   
        - ./tomcat/context.xml:/usr/local/tomcat/conf

volumes:
    mysql-data:

